### PR TITLE
Fixed grey food scores displayed for cosmetics

### LINKED ISSUE #3741: OBF - Grey scores are displayed for cosmetics
**OBF - Grey food scores are displayed for cosmetics**
image

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Added a _if_ block to check the build flavor. If the build flavor is  **"off"** then only the food scores are visible. 

#### Related issues
Fixes #3741

#### Related PRs
None

#### Screenshots
img

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/adapters/ProductsRecyclerViewAdapter.kt [hunk 1]
```diff
@@ -80,23 +81,22 @@ class ProductsRecyclerViewAdapter(
...
-        holder.productNova.setImageResource(novaRes)
-        holder.productNova.visibility = View.VISIBLE
-
-
-        // Set ecoscore icon
-        val ecoRes = product.getEcoscoreResource()
-        holder.productEcoscore.setImageResource(ecoRes)
-        holder.productEcoscore.visibility = View.VISIBLE
-
+        if(BuildConfig.FLAVOR == "off") {
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/adapters/ProductsRecyclerViewAdapter.kt]: Use `AppFlavors.isFlavors(AppFlavors.OFF)`

**Review by VaiTon — CHANGES_REQUESTED** [review]

**Comment by mrudultora** [comment]
@VaiTon Changes done accordingly !

**Review by VaiTon — APPROVED** [review]
