### PR TITLE
Closes #1954 Fix crash on navigating back from search by barcode

### LINKED ISSUE #1943: The dynamic product count slows down the app
The dynamic product count slows down the app. It would probably make sense to cache the number, and adding pull to refresh.

Adding pull to refresh would also open the way to a more dynamic home in the future.

### LINKED ISSUE #1954: App crashes on pressing back button from search by barcode
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
App crashes on pressing back button from search by barcode screen.

**Steps to reproduce:** 
- Open the app.
- Navigate to "Search by barcode" menu from the navigation pane.
- Press back button.

**Add system logs:**
```
openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 4117
    java.lang.IllegalStateException: Fragment HomeFragment{2eb61ce} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
        at android.support.v4.app.Fragment.getResources(Fragment.java:678)
        at openfoodfacts.github.scrachx.openfood.fragments.HomeFragment$1.onResponse(HomeFragment.java:73)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Expected behavior:** 
The app shouldn't crash.

**Observed behavior:** 
The app crashes.

**Device and Android version:** 
Motorola Moto G5s
Android 8.1

**Screenshots:** 
<kbd>videotogif_2018 10 04_01 43 00</kbd>

### PR DESCRIPTION
**Pull request by huzaifaiftikhar**
## Description
- Used `OFFApplication.getInstance()` to get the string resource to prevent crash.
- Removed lint warnings from the `HomeFragment.java`.
- Changed the endpoint of getting the total products count from `/1.json` to `/1.json?fields=null` and thus reducing the size of the json from **354.5 kB (3,54,485 bytes)** to **124 bytes**.
- Also cache the total products count and use it in the absence of internet connection.

## Related issues and discussion
Fixes #1954 
Probably Fixes #1943
 
 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines.

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java [hunk 1]
```diff
@@ -47,6 +54,8 @@
     TextView textHome;
 
     private OpenFoodAPIService apiClient;
+    private SharedPreferences.Editor editor;
```
Comment (brandenfung) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java]: editor can be a local variable

Comment (huzaifaiftikhar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/HomeFragment.java]: Done

**Comment by teolemon** [comment]
Converted to shared.
Thanks @huzaifaiftikhar thanks @brandenfung for reviewing :-)
