### PR TITLE
fixes #2309 :  Add Error Message for empty Password in Sign-in Screen 

### LINKED ISSUE #2309: Add Error message for empty Password in Sign-in Screen
**Summary:** 

With empty credentials, on clicking Sign in button, error message pops up only for Username and not for password.

**Steps to reproduce:** 

Step 1. Navigate to Login Screen.
Step 2. Leave the credentials empty.
Step 3. Click the Sign In button.
Step 4. Observer the error

**Expected behavior:** 

An error message should have popped up for password as well.

**Observed behavior:** 

Error message popped up only for username field.

**Device and Android version:** 

Device: Lenovo Vibe K5 Note
Android version: Android 6.0 Marshmallow

**Screenshots:** 

screenshot_2019-02-26-01-25-44-144

### PR DESCRIPTION
**Pull request by mustaqmustu**
## Description
updated loginActivity.java
## Related issues and discussion
#2309 
Screenshots:
errror

 ## Checklist
 
Make sure you've done all the following (You can delete the checklist before submitting)
 
 - [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
 - [x] Code is well documented
 - [x] Include unit tests for new functionality
 - [x] All user-visible strings are made translatable
 - [x] Code passes Travis builds in your branch
 - [x] If you have multiple commits please combine them into one commit by squashing them.
 - [x] Read and understood the contribution guidelines .

### CODE REVIEW

**Comment by mustaqmustu** [comment]
@teolemon as u said in https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2310,I opened this PR for an already claimed issue.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java [hunk 1]
```diff
@@ -154,6 +154,11 @@ protected void attemptLogin() {
             loginView.requestFocus();
             return;
         }
+        if (TextUtils.isEmpty(password)) {
+            Toast.makeText(this, getString(R.string.error_field_required), Toast.LENGTH_SHORT).show();
```
Comment (Karljoones) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: Can you please set this as an error on the password view, rather than a toast, just to make sure that it is kept consistent. Check out a couple of lines below.

Comment (mustaqmustu) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: @Karljoones  I used toast because to keep consistent as I refer to the PR I made in past i.e..https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2295

Comment (brandenfung) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: Text field error messages should be in the password view as described by @Karljoones . In the login activity, we are using `TextInputLayout`. The reason the icons are overlapping is because we should actually be setting the error message to this layout and not the Edit Text view. 

See here for more information: https://material.io/develop/android/components/text-input-layout/

Comment (mustaqmustu) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: @Karljoones I have made the required changes,Check it out once :)

**Comment by Karljoones** [comment]
Good, merged, thanks!
