### PR TITLE
Fixes Issue #2030 Added reload functionality as soon as product is ed…

### LINKED ISSUE #2029: Immediately attempt to reload the product when ingredient are added or modified
- Immediately attempt to reload the product when ingredient are added or modified
- Usually we can compute additives, allergens, and the Nova groups, and they need to appear instantly.

### LINKED ISSUE #2030: Immediately attempt to reload the product when the category is added or modified
- Immediately attempt to reload the product when the category is added or modified. That way it will show the Nutri-Score
- Usually we can compute the Nutri-Score if nutrition is here, and it needs to appear instantly.

### PR DESCRIPTION
**Pull request by prashantkh19**
## Related issues and discussion
#fixes #2030
#fixes #2029

### CODE REVIEW

**Comment by teolemon** [comment]
Anyone also getting this while attempting to build (on apk install)
```
Error while executing: am start -n "openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.splash.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=openfoodfacts.github.scrachx.openfood/.views.splash.SplashActivity }
Error type 3
Error: Activity class {openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.splash.SplashActivity} does not exist.

Error while Launching activity
```

**Comment by teolemon** [comment]
Not working for me. Either after pressing save or trying to pull to refresh.

**Comment by prashantkh19** [comment]
> Not working for me. Either after pressing save or trying to pull to refresh.

I will look into it.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java [hunk 1]
```diff
@@ -54,475 +62,425 @@
...
-					Utils.scan( ProductActivity.this );
-				}
-			}
-		} );
-
-		bottomNavigationView.setOnNavigationItemSelectedListener( item -> {
-
-			switch( item.getItemId() )
-			{
+public class ProductActivity extends BaseActivity implements OnRefreshListener {
```
Comment (PrajwalM2212) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java]: @prashantkh19  Why do you delete the entire thing again and paste it again ? 

This PR has 451 deletions and 417 additions.  Seeing this number it seems that the number of genuine changes that you have made will be less than 50 lines.  

*If the diff in the PR contained only the changes you made, it would be far easier to review. *
 *At this state it is impossible to determine what changes you have made and what was present earlier. *

Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java]: > @prashantkh19 Why do you delete the entire thing again and paste it again ?
> 
> This PR has 451 deletions and 417 additions. Seeing this number it seems that the number of genuine changes that you have made will be less than 50 lines.
> 
> If the diff in the PR contained only the changes you made, it would be far easier to review.
> At this state it is impossible to determine what changes you have made and what was present earlier.

@PrajwalM2212 I am sorry, I am new to open source, didn't think this would create problems. I will take care of this next time.

Comment (PrajwalM2212) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java]: @prashantkh19  The PR should ideally contain only the genuine changes that you have made. This way the diff will show only the changes that you have made to the existing codebase. That way reviewers can validate if your changes are good or not

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java [hunk 2]
```diff
@@ -54,475 +62,425 @@
...
+    @Override
+    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
+        super.onActivityResult(requestCode, resultCode, data);
+        if (requestCode == LOGIN_ACTIVITY_REQUEST_CODE && resultCode == RESULT_OK) {
+            Intent intent = new Intent(ProductActivity.this, AddProductActivity.class);
+            intent.putExtra("edit_product", mState.getProduct());
+            startActivityForResult(intent, EDIT_REQUEST_CODE);
+        }
+        if (requestCode == EDIT_REQUEST_CODE && resultCode == RESULT_OK) {
+            api.getProduct(mState.getProduct().getCode(), this);
```
[the remark this answers is not in the document]
Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java]: I will modify it.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/AddProductActivity.java [hunk 3]
```diff
@@ -922,6 +922,8 @@ public void onSuccess(State state) {
                         toast.show();
                         mOfflineSavedProductDao.deleteInTx(mOfflineSavedProductDao.queryBuilder().where(OfflineSavedProductDao.Properties.Barcode.eq(code)).list());
                         Intent intent = new Intent();
+                        state.setProduct(mProduct);
+                        intent.putExtra("state", state);
```
[the remark this answers is not in the document]
Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/AddProductActivity.java]: Sorry, I added this for my previous approach to solving this. I will remove this.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIClient.java [hunk 4]
```diff
@@ -14,6 +14,10 @@
 import com.afollestad.materialdialogs.MaterialDialog;
 import com.fasterxml.jackson.databind.JsonNode;
 import com.firebase.jobdispatcher.JobParameters;
+
+import io.reactivex.SingleObserver;
+import io.reactivex.android.schedulers.AndroidSchedulers;
+import io.reactivex.disposables.Disposable;
```
[the remark this answers is not in the document]
Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIClient.java]: I will

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java (hunk 1 above)
Comment (huzaifaiftikhar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ProductActivity.java]: He just reformatted the entire file. It's alright! From next time onwards you can create a separate PR for reformatting if there are a lot of changes regarding the formatting.

**Comment by huzaifaiftikhar** [comment]
The issue still seems to persist, steps to reproduce :
- Try editing a barcode (use the test product with barcode "1")
- Remove everything from the categories list and save the product.
- The categories are removed successfully as expected.
- Edit the product again, You could see that all the previous categories that you removed are still present in the editing activity. (Ideally the categories should have been blank)
- Add some more categories or leave everything as it is since the previous categories are already listed in the editing activity. Save the product.
- Refresh the product, the categories that we re-added doesn't appear even on refresh.

I guess partial addition and deletion of categories works but complete removal and then adding again doesn't.

**Comment by teolemon** [comment]
@prashantkh19 @huzaifaiftikhar just built the latest revision
From purely the functional side:
Tried adding a category to compute the Nutri-Score: works 
Tried adding an additionnal category: works
Tried removing the category : works
Tried removing all categories: works

**Comment by teolemon** [comment]
@prashantkh19 Can you expand the mechanism to the other fields (brand, quantity, labels, packaging…)?

**Comment by teolemon** [comment]
@prashantkh19 it's related to timeouts on one of the 4 builds. That's not related to your changes :-)
We usually relaunch it.

**Comment by teolemon** [comment]
Tiny merge conflict to solve

**Comment by teolemon** [comment]
Can you solve the little conflict ?
