### PR TITLE
Fix duplicated allergen display bug

### LINKED ISSUE #2077: The allergen popup behaves weirdly
image
image
image
To reproduce, you need a product with an allergen like 3245412051661, and then switch from ingredient tab to the main tab and back, to retrigger the modal several times

### PR DESCRIPTION
**Pull request by raphael0202**
## Description

#fixes #2077

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/summary/SummaryProductFragment.java [hunk 1]
```diff
@@ -589,39 +589,48 @@ public void showAdditivesState(String state) {
...
-        if (!allergens.isEmpty() && product.getStatesTags().get(0).contains("to-be-completed")) {
-            productIncompleteView.setVisibility(View.VISIBLE);
+        if (allergens.isEmpty()) {
+            return;
         }
 
-        List<String> matchAll = new ArrayList<>();
-        for (int a = 0; a < allergens.size(); a++) {
-            for (int i = 0; i < productAllergens.size(); i++) {
+        if (!product.getStatesTags().contains("en:ingredients-completed")) {
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/summary/SummaryProductFragment.java]: @stephanegigandet is that a sound idea ? We used to ask for product complete.

**Comment by teolemon** [comment]
Thanks @raphael0202 :-)
