### PR TITLE
Closes #996  Login issue fixed

### LINKED ISSUE #996: Already Login is displayed when User is not logged in
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting a issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
The app shows a popup of already logged in when the user is actually not logged in.

**Steps to reproduce:** 
* reinstall the latest build 
* open Sign in

**Expected behavior:** 
directly go to Sign in if the user is not signed in.

**Device and Android version:** 
7.0 

**Screenshots:**

### PR DESCRIPTION
**Pull request by danzzen**
## Description

issue:   #996 Sign in option even after signing in.
Now logout option will appear until user don't logout.

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java [hunk 1]
```diff
@@ -92,22 +93,19 @@ protected void onCreate(Bundle savedInstanceState) {
 
     @OnClick(R.id.buttonSave)
     protected void attemptLogin() {
-        String login = loginView.getText().toString();
+        String login = loginView.getText().toString().trim();
```
Comment (Karljoones) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: This can not be trimmed, as discussed in the previous PR, whitespace is a valid character.

Comment (danzzen) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: Ok i will remove that part

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java [hunk 2]
```diff
@@ -147,7 +145,7 @@ public void onResponse(Call<ResponseBody> call, Response<ResponseBody> response)
                 } else {
                     // store the user session id (user_session and user_id)
                     for (HttpCookie httpCookie : HttpCookie.parse(response.headers().get("set-cookie"))) {
-                        if (httpCookie.getDomain().equals(".openfoodfacts.org") && httpCookie.getPath().equals("/")) {
+                        if (httpCookie.getDomain().equals(".openbeautyfacts.org") && httpCookie.getPath().equals("/")) {
```
Comment (policorn) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: shouldn't this domain string be based on the flavor instead?

Comment (danzzen) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: But the Domain returned after login is this .openbeautyfacts.org

Comment (danzzen) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: @policorn sry i didn't get what you said. I printed the log and find that Domain name is .openbeautyfacts.org not the .openfoodfacts.org so comparing httpCookie.getDomain() with .openbeautyfacts.org will set the condition true and we will store the user and session and it will resolve the issue #996

Comment (Karljoones) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: I think what he is trying to say is that depending on the current flavour of the app, the domain should change.

If it is the OFF flavor, use `.openfoodfacts.org`
If it is the OBF flavor use `.openbeautfyfacts.org`

Comment (teolemon) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: .openpetfoodfacts.org for OPFF

Comment (policorn) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: Thanks @Karljoones, that's right; sorry @danzzen I wasn't more clear

Comment (danzzen) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: No problem @policorn

**Comment by policorn** [comment]
Thanks @danzzen, @Karljoones! Merged
