### PR TITLE
Rename Server attribute and Fixed layout 

### LINKED ISSUE #3665: Add bottom padding to the attributes view (impossible to scroll completely)
- [ ] Add bottom padding to the attributes view since it's impossible to scroll completely right now. 
- [ ] Also let's rename the tab to "Synthesis" while it's still in progress.

image

### PR DESCRIPTION
**Pull request by kartikaysharma01**
####  Description
Synthesis Layout fixed 

#### Related issues

Fixes #3665

#### Screenshots

image

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt [hunk 1]
```diff
@@ -262,7 +262,7 @@ class ProductViewActivity : BaseActivity(), OnRefreshListener {
                 adapter.addFragment(ContributorsFragment.newInstance(productState), activity.getString(R.string.contribution_tab))
             }
 
-            if (isFlavors(OFF)) adapter.addFragment(ServerAttributesFragment().applyBundle(fBundle), "Server attributes")
+            if (isFlavors(OFF)) adapter.addFragment(ServerAttributesFragment().applyBundle(fBundle), "Synthesis")
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt]: I initially used a string but it would be better if we used a resource. Could you add this to the title names array in res?

**Review by VaiTon — COMMENTED** [review]
All good! Just a reminder.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt (hunk 1 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt]: On it.

Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt]: I made the change.

**Review by VaiTon — APPROVED** [review]

**Comment by VaiTon** [comment]
Thank you! 🎉
