### PR TITLE
Fixes #1093 Last seen of Product Issue

### LINKED ISSUE #1093: Issue in  time for the product in history page
**Summary:** 

the time shown is  "1 minutes ago" or "1 hours ago". Rather it should be "1 minute ago" or "1 hour ago".
**Steps to reproduce:** 

menu -> history -> see for an item viewed an hour ago or a minute ago

**Screenshots:** 

screenshot_20180304-114035

### PR DESCRIPTION
**Pull request by ManavPoddar**
## Description

Added checks for Minutes, Hours and days

## Related issues and discussion
#1093 
 
 ## Screen-shots, if any
 
screenshot_20180304-121702

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java [hunk 1]
```diff
@@ -88,17 +88,35 @@ public void calcTime(Date date, HistoryScanHolder holder) {
...
         String secText = String.valueOf(seconds) + " seconds ago";
+
         String minText = String.valueOf(minutes) + " minutes ago";
+        String OneMinText = String.valueOf(minutes) + " minute ago";
+
         String hourText = String.valueOf(hours) + " hours ago";
+        String OneHourText = String.valueOf(hours) + " hour ago";
+
         String dayText = String.valueOf(days) + " days ago";
+        String OneDayText = String.valueOf(days) + " day ago";
```
Comment (Karljoones) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: You should use <plural> here to take care of this. This is better for localisation. You should use:
- One
- Two
- Few
- Many
- Other

While English will be easy since two, few, many and other will be the same but this is not the case in every language.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java [hunk 2]
```diff
@@ -88,17 +88,35 @@ public void calcTime(Date date, HistoryScanHolder holder) {
...
 
         if (seconds < 60) {
             holder.txtDate.setText(secText);
-        } else if (minutes < 60) {
+        }
+        else if(minutes==1){
```
Comment (PrajwalM2212) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: (minutes == 1 ) condition will overlap with the condition (minutes <60) as one minute is less than 60 minutes .

Comment (PrajwalM2212) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: The same with hour and day.

Comment (PrajwalM2212) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: Try to add the (minute == 1) condition inside (minutes<60)condition . This will prevent overlap and make (minute == 1) a subset of (minutes<60) condition.

Comment (Karljoones) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: @PrajwalM2212 Please see my above requested changes, this will not need to be done once my changes are implemented.

Comment (PrajwalM2212) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: @Karljoones  Yes . I will delete this comment .

**Comment by PrajwalM2212** [comment]
@ManavPoddar  Implement changes suggested by @Karljoones only .

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java (hunk 2 above)
Comment (ManavPoddar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: Hey @PrajwalM2212 , In my Humble Opinion the control flow for how else if conditions are designed inherently will take care of the specific flaw you are pointing out. Thanks, I'm already  working on @Karljoones  changes.

Comment (PrajwalM2212) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/adapters/HistoryListAdapter.java]: @ManavPoddar  I know . I pointed out the issue to make the code look good and easily understandable for future developers.

**Comment by ManavPoddar** [comment]
Hey @Karljoones , used plurals, please review the PR :)

**Comment by Karljoones** [comment]
Merged, thanks @ManavPoddar
