### PR TITLE
Closes #1247: add search feature to ProductBrowsingListActivity (Product list).

### LINKED ISSUE #1247: ProductBrowsingListActivity search feature missing
**Summary:** 

When the user start search about product from Home and move to ProductBrowsingListActivity (Product list) he can't make a search query again until back to home again by pressing back arrow and make new search query from home which is not good UX for user.

**Steps to reproduce:** 

How can we reproduce the issue?

**Expected behavior:** 

Search feature add to products list.

**Screenshots:** 
Current State:
screenshot_1521077763
Expected:
screenshot_1521077763

### PR DESCRIPTION
**Pull request by MohamedHefny**
## Description

Search feature now add to ProductBrowsingListActivity (Product list), so the user now can make multiply search query from product list activity without go back to home.

## Related issues and discussion
{#1247}
ProductBrowsingListActivity search feature missing.
 
 ## Screen-shots, if any
 
screenshot_1521078734

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java [hunk 1]
```diff
@@ -87,6 +129,11 @@ protected void onCreate(Bundle savedInstanceState) {
         searchType = extras.getString(SEARCH_TYPE);
```
Comment (Shubham2320) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java]: I think in this case we should always set search type to search as it would not work well for categories, labels, stores etc.

**Comment by Shubham2320** [comment]
Travis-CI test is failed probably because of lint errors and also it didn't pass some of the test cases. Pleases have a look.

**log:**

Ran lint on variant opffRelease: 1690 issues found
Ran lint on variant obfRelease: 1680 issues found
Ran lint on variant opffDebug: 1690 issues found
Ran lint on variant offDebug: 1680 issues found
Ran lint on variant offRelease: 1680 issues found
Ran lint on variant obfDebug: 1680 issues found
Wrote HTML report to file:///home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/reports/lint-results.html
Wrote XML report to file:///home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/build/reports/lint-results.xml
:app:preObfDebugUnitTestBuild UP-TO-DATE
:app:javaPreCompileObfDebugUnitTest
:app:compileObfDebugUnitTestJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:app:mockableAndroidJar
:app:processObfDebugUnitTestJavaRes
:app:testObfDebugUnitTest
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > getProductByNutritionGrade_a_productsFound FAILED
    java.lang.AssertionError at OpenFoodAPIServiceTest.java:275
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byCategory FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:98
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byIngredient FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:168
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > getProductByTrace_eggs_productsFound FAILED
    java.lang.AssertionError at OpenFoodAPIServiceTest.java:275
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > getProductByCity_Paris_noProductFound FAILED
    java.lang.AssertionError at OpenFoodAPIServiceTest.java:283
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byPurchasePlace FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:138
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > getProductByAdditive_e301_productsFound FAILED
    java.lang.AssertionError at OpenFoodAPIServiceTest.java:275
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byBrand FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:128
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byLabel FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:88
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byState FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:108
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byStore FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:148
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byTrace FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:178
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > getProductByPackagerCode_emb35069c_productsFound FAILED
    java.lang.AssertionError at OpenFoodAPIServiceTest.java:275
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byLanguage FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:78
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byPackaging FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:118
openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIServiceTest > byCountry FAILED
    junit.framework.AssertionFailedError at OpenFoodAPIServiceTest.java:158
26 tests completed, 16 failed
:app:testObfDebugUnitTest FAILED

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java (hunk 1 above)
Comment (MohamedHefny) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java]: I think so, but i let this because there is a switch statement on this variable in this activity, so it will maybe used to do another functionality in the future, but until this time the search type variable always set  to SEARCH.

Comment (Shubham2320) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/ProductBrowsingListActivity.java]: Fine then. :)

**Comment by MohamedHefny** [comment]
@Shubham2320 I'm trying to be familiar with Travis-CI and work with Travis-CI test error, but i think at this point i need some help to solve this problem.

**Comment by MohamedHefny** [comment]
@Karljoones Please check for merging.

**Comment by Karljoones** [comment]
Merged, thanks @MohamedHefny
