### PR TITLE
Fixes: Unable to open Server Attributes in product screen and product from category

### LINKED ISSUE #3660: Unable to open Server Attributes in product screen and product from category
**Describe the bug**
Unable to open Server Attributes in product screen and product from category 

**To Reproduce**
In develop branch:
1. Go to categories
2. Click on any category
3. Open any product

In develop branch:
1. Go to any product
2. Click on server attributes
3. See error

**Expected behavior**
No error should come

### PR DESCRIPTION
**Pull request by kartikaysharma01**
####  Description
Fixed the issue by completing a missing part of code.

#### Related issues
Fixes #3660

#### Screenshots
image

(I removed the video - Pierre - the eco-score is not yet released)

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 1]
```diff
@@ -683,7 +683,7 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
     }
 
     private fun getEmbUrl(embTag: String) =
-            mTagDao.queryBuilder().where(TagDao.Properties.Id.eq(embTag)).unique().name
+            mTagDao.queryBuilder().where(TagDao.Properties.Id.eq(embTag)).unique().name ?: embTag
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Why are this and the method below the exact same thing?

**Comment by teolemon** [comment]
I removed the video since the Eco-Score is not out officially yet.

**Review by VaiTon — APPROVED** [review]
