### PR TITLE
Closes #1826: java.lang.IllegalStateException android.widget.TextView.onKeyUp

### LINKED ISSUE #1826: java.lang.IllegalStateException  android.widget.TextView.onKeyUp
BlackBerry PRIV by BlackBerry (venice), Android 6.0
```

java.lang.IllegalStateExceptionj : 
  at android.widget.TextView.onKeyUp (TextView.java:6244)
  at android.view.KeyEvent.dispatch (KeyEvent.java:2673)
  at android.view.View.dispatchKeyEvent (View.java:9253)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.widget.ScrollView.dispatchKeyEvent (ScrollView.java:379)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.support.v4.view.ViewPager.dispatchKeyEvent (ViewPager.java)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at android.view.ViewGroup.dispatchKeyEvent (ViewGroup.java:1641)
  at com.android.internal.policy.PhoneWindow$DecorView.superDispatchKeyEvent (PhoneWindow.java:2401)
  at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent (PhoneWindow.java:1727)
  at android.app.Activity.dispatchKeyEvent (Activity.java:2736)
  at android.support.v7.app.AppCompatActivity.dispatchKeyEvent (AppCompatActivity.java)
  at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent (WindowCallbackWrapper.java)
  at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent (AppCompatDelegateImplBase.java)
  at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent (PhoneWindow.java:2316)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent (ViewRootImpl.java:4173)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:4135)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3669)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3722)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3688)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:3814)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3696)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:3871)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3669)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:3722)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:3688)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:3696)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:3669)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:6510)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:6454)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:6415)
  at android.view.ViewRootImpl$ViewRootHandler.handleMessage (ViewRootImpl.java:3461)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:148)
  at android.app.ActivityThread.main (ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:764)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:626)
```

### PR DESCRIPTION
**Pull request by jaindiv26**
## Description
The issue #1826 was caused because the Edittext input method option(ime) was not set, so it by default seek for next focusable object, since it was not created, maybe in Blackberry Priv due to hardware keyboard it might have crashed the app, so I've set the ime option done in the last Edittext i.e (Alcohol Field) and same in the Java file (AddProductNutritionFactsFragment).

## Related issues and discussion
#1826 : java.lang.IllegalStateException android.widget.TextView.onKeyUp
 
 ## Screen-shots, if any
 
44158851-6ce09000-a0d3-11e8-8471-309ffdd634ae

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java [hunk 1]
```diff
@@ -1070,6 +1071,7 @@ private void addNutrientRow(int position, CharSequence text, boolean preFillValu
         editText.setHint(text);
         editText.setId(position);
         editText.setKeyListener(keyListener);
+        editText.setImeOptions(EditorInfo.IME_ACTION_DONE);
```
Comment (huzaifaiftikhar) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: I guess we won't be able to move to the next nutrition facts field using the soft key if we add this to each extra nutrient we add.

File: app/src/main/res/layout/fragment_add_product_nutrition_facts.xml [hunk 2]
```diff
@@ -514,6 +514,7 @@
                 android:gravity="center_vertical"
                 android:hint="@string/nutrition_alcohol"
                 android:inputType="textVisiblePassword"
+                android:imeOptions="actionDone"
```
Comment (huzaifaiftikhar) [inline app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: Again we might not be able to go to the additional nutrients from the alcohol field using the soft keyboard​. Can't we use `android:nextFocusDown` instead of action done since it is used for physical keys.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java (hunk 1 above)
Comment (jaindiv26) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @huzaifaiftikhar If I've selected multiple nutrients and put IME_ACTION-DONE in addNutrientRow() method then, all the added nutrient will dismiss keyboard when press IME button. The only way I think of it is to store all EditText in an ArrayList and then put a check that, if the position is n-1 then put IME_ACTION_DONE else nextFocusDown. But the risk is that, if the ArrayList is empty then it will crash the application. So, guide me on this issue.

Comment (huzaifaiftikhar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @jaindiv26 I guess if we add `IME_ACTION_NEXT` instead it will work too. After the last field the focus goes back to the first field. Also I am not sure if this would solve the issue which this PR is targeting. Even in the absence of ime options the app should not crash. What's your thought on this?

Comment (jaindiv26) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @huzaifaiftikhar IME.ACTION.DONE or NEXT calls to find the next focus item that should be quickly jumped to, but this does not exist or isn't focusable, it throws this error (java.lang.IllegalStateException android.widget.TextView.onKeyUp). It will happen if the next is hidden and thus not focusable or the parent cannot actually deal with the findFocus() call and returns null.

https://stackoverflow.com/questions/13614101/fatal-crash-focus-search-returned-a-view-that-wasnt-able-to-take-focus/14189135

Comment (huzaifaiftikhar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: Thanks for the link. I read all the answers however I still have a doubt. This is happening when the user has defined the ime options either to NEXT or PREVIOUS, however in our case we have not defined the ime options and it has a default behaviour. According to your answer it means that it is necessary to define the ime options to every edit text we use in an android app or else the app would crash. This doesn't seem correct to me. Do you have a device where you can actually reproduce this?

Comment (jaindiv26) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @huzaifaiftikhar I've tried every scenario on various devices but, can't reproduce this issue, I think this issue happens on devices with a hardware keyboard support. I've one possible solution in mind, let me implement it and see the results.

File: app/src/main/res/layout/fragment_add_product_nutrition_facts.xml (hunk 2 above)
Comment (Karljoones) [reply app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: @jaindiv26 @huzaifaiftikhar Realistically, you would want `actionNext` on every edittext to ensure that the app drops down to the next available text area, and then `actionDone` on the final one.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java (hunk 1 above)
Comment (huzaifaiftikhar) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @jaindiv26 It seems like the issue is not limited to devices with a hardware keyboard. We have crash reports for devices with a soft keyboard as well. Check the latest comments on the [issue](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1826).

Comment (jaindiv26) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductNutritionFactsFragment.java]: @huzaifaiftikhar @Karljoones Let me try it, one more time.

File: app/src/main/res/layout/fragment_add_product_nutrition_facts.xml (hunk 2 above)
Comment (jinqian) [reply app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: +1, I agree with @Karljoones :)

Comment (jaindiv26) [reply app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: @teolemon @Karljoones @huzaifaiftikhar I've solved this issue. Check out this screen recording. https://drive.google.com/file/d/1NDfmJxsHMsT0fL1wyv4y6uLSmHJzqgz9/view?usp=sharing

Comment (jaindiv26) [reply app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: @Karljoones @huzaifaiftikhar I've saved the last edit text in a variable and when a new edit text is created last edit text nextFocusDown is set to new one set the IME option of the last edit text to DONE and save the newly created edit text to the variable, you can see the result in the screen recording.

Comment (jaindiv26) [reply app/src/main/res/layout/fragment_add_product_nutrition_facts.xml]: @teolemon @Karljoones @huzaifaiftikhar Any updates?

**Comment by jaindiv26** [comment]
@Karljoones @huzaifaiftikhar @teolemon Any updates
