### PR TITLE
Fixes Issues #2065 #2066 #2067: Added Other Information, Storage Inst…

### LINKED ISSUE #2065: Adding support for recycling instructions
We have two new fields for some products:
```
recycling_instructions_to_discard_fr
recycling_instructions_to_recycle_fr
```
(You can append language for language specific versions)

### PR DESCRIPTION
**Pull request by prashantkh19**
…ructions and Recycling details to the product details.

## Description
Added Other information, storage instructions and recycling instructions to the product activity and addProduct activity.

## Related issues and discussion
#fixes #2065 #2066 #2067 
 
 ## Screen-shots

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 1]
```diff
@@ -112,6 +112,10 @@
     private static final String PARAM_PURCHASE = "add_purchase_places";
     private static final String PARAM_STORE = "add_stores";
     private static final String PARAM_COUNTRIES = "add_countries";
+    private static final String PARAM_OTHER_INFO = "other_information_fr";
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]: Can you use `other_information` instead, so that it can work accross languages ?
Ideally, we should retrieve it based on the locale, but we don't do it yet for fields like common_name or product_name.

**Comment by prashantkh19** [comment]
Edit is not working yet. I think there is a need to update the server side script for that (cgi/product_jqm2.pl).

**Comment by teolemon** [comment]
No, edit is not operational yet. This is outside the scope for now.
cc @stephanegigandet

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java (hunk 1 above)
Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]: Okay, I will do it for all new four fields.

**Comment by teolemon** [comment]
@prashantkh19 Can you solve the tiny merge conflict, and also disable the fields in edit mode ?

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java [hunk 2]
```diff
@@ -129,12 +129,19 @@ public String convert(String value) {
     private String nutritionDataPer;
     @JsonProperty("no_nutrition_data")
     private String noNutritionData;
+    @JsonProperty("other_information_fr")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java]:
```suggestion
    @JsonProperty("other_information")
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java [hunk 3]
```diff
@@ -129,12 +129,19 @@ public String convert(String value) {
...
+    private String otherInformation;
+    @JsonProperty("conservation_conditions_fr")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java]:
```suggestion
    @JsonProperty("conservation_conditions")
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java [hunk 4]
```diff
@@ -129,12 +129,19 @@ public String convert(String value) {
...
+    private String conservationConditions;
+    @JsonProperty("recycling_instructions_to_discard_fr")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java]:
```suggestion
    @JsonProperty("recycling_instructions_to_discard")
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java [hunk 5]
```diff
@@ -129,12 +129,19 @@ public String convert(String value) {
...
+    private String recyclingInstructionsToDiscard;
+    @JsonProperty("recycling_instructions_to_recycle_fr")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/models/Product.java]:
```suggestion
    @JsonProperty("recycling_instructions_to_recycle")
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java [hunk 6]
```diff
@@ -24,7 +36,7 @@
...
+    @GET("api/v0/product/{barcode}.json?fields=image_small_url,vitamins_tags,minerals_tags,amino_acids_tags,other_nutritional_substances_tags,image_front_url,image_ingredients_url,image_nutrition_url,url,code,traces_tags,ingredients_that_may_be_from_palm_oil_tags,additives_tags,allergens_hierarchy,manufacturing_places,nutriments,ingredients_from_palm_oil_tags,brands_tags,traces,categories_tags,ingredients_text,product_name,generic_name,ingredients_from_or_that_may_be_from_palm_oil_n,serving_size,allergens_tags,allergens,origins,stores,nutrition_grade_fr,nutrient_levels,countries,countries_tags,brands,packaging,labels_tags,labels_hierarchy,cities_tags,quantity,ingredients_from_palm_oil_n,image_url,link,emb_codes_tags,states_tags,creator,created_t,last_modified_t,last_modified_by,editors_tags,nova_groups,lang,purchase_places,nutrition_data_per,no_nutrition_data,other,other_information_fr,conservation_conditions_fr,recycling_instructions_to_discard_fr,recycling_instructions_to_recycle_fr,warning,customer_service")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java]:
```suggestion
    @GET("api/v0/product/{barcode}.json?fields=image_small_url,vitamins_tags,minerals_tags,amino_acids_tags,other_nutritional_substances_tags,image_front_url,image_ingredients_url,image_nutrition_url,url,code,traces_tags,ingredients_that_may_be_from_palm_oil_tags,additives_tags,allergens_hierarchy,manufacturing_places,nutriments,ingredients_from_palm_oil_tags,brands_tags,traces,categories_tags,ingredients_text,product_name,generic_name,ingredients_from_or_that_may_be_from_palm_oil_n,serving_size,allergens_tags,allergens,origins,stores,nutrition_grade_fr,nutrient_levels,countries,countries_tags,brands,packaging,labels_tags,labels_hierarchy,cities_tags,quantity,ingredients_from_palm_oil_n,image_url,link,emb_codes_tags,states_tags,creator,created_t,last_modified_t,last_modified_by,editors_tags,nova_groups,lang,purchase_places,nutrition_data_per,no_nutrition_data,other,other_information,conservation_conditions,recycling_instructions_to_discard,recycling_instructions_to_recycle,warning,customer_service")
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java [hunk 7]
```diff
@@ -33,7 +45,7 @@
...
+    @GET("api/v0/product/{barcode}.json?fields=image_small_url,vitamins_tags,minerals_tags,amino_acids_tags,other_nutritional_substances_tags,image_front_url,image_ingredients_url,image_nutrition_url,url,code,traces_tags,ingredients_that_may_be_from_palm_oil_tags,additives_tags,allergens_hierarchy,manufacturing_places,nutriments,ingredients_from_palm_oil_tags,brands_tags,traces,categories_tags,ingredients_text,product_name,generic_name,ingredients_from_or_that_may_be_from_palm_oil_n,serving_size,allergens_tags,allergens,origins,stores,nutrition_grade_fr,nutrient_levels,countries,countries_tags,brands,packaging,labels_tags,labels_hierarchy,cities_tags,quantity,ingredients_from_palm_oil_n,image_url,link,emb_codes_tags,states_tags,creator,created_t,last_modified_t,last_modified_by,editors_tags,nova_groups,lang,purchase_places,nutrition_data_per,no_nutrition_data,other_information_fr,conservation_conditions_fr,recycling_instructions_to_discard_fr,recycling_instructions_to_recycle_fr,warning,customer_service")
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIService.java]:
```suggestion
    @GET("api/v0/product/{barcode}.json?fields=image_small_url,vitamins_tags,minerals_tags,amino_acids_tags,other_nutritional_substances_tags,image_front_url,image_ingredients_url,image_nutrition_url,url,code,traces_tags,ingredients_that_may_be_from_palm_oil_tags,additives_tags,allergens_hierarchy,manufacturing_places,nutriments,ingredients_from_palm_oil_tags,brands_tags,traces,categories_tags,ingredients_text,product_name,generic_name,ingredients_from_or_that_may_be_from_palm_oil_n,serving_size,allergens_tags,allergens,origins,stores,nutrition_grade_fr,nutrient_levels,countries,countries_tags,brands,packaging,labels_tags,labels_hierarchy,cities_tags,quantity,ingredients_from_palm_oil_n,image_url,link,emb_codes_tags,states_tags,creator,created_t,last_modified_t,last_modified_by,editors_tags,nova_groups,lang,purchase_places,nutrition_data_per,no_nutrition_data,other_information,conservation_conditions,recycling_instructions_to_discard,recycling_instructions_to_recycle,warning,customer_service")
```

**Comment by teolemon** [comment]
I've fixed the fields @prashantkh19 
You need to accept them. @jinqian made a remark about variable that can be extracted

**Comment by teolemon** [comment]
```
Caused by: Error: Attribute "android:id" was already specified for element "TextView".
	at com.android.ide.common.resources.MergedResourceWriter.end(MergedResourceWriter.java:305)
	at com.android.ide.common.resources.DataMerger.mergeData(DataMerger.java:293)
	at com.android.ide.common.resources.ResourceMerger.mergeData(ResourceMerger.java:384)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:316)
	... 116 more
Caused by: org.xml.sax.SAXParseException; systemId: file:/home/travis/build/openfoodfacts/openfoodfacts-androidapp/app/src/main/res/layout/fragment_summary_product.xml; lineNumber: 577; columnNumber: 54; Attribute "android:id" was already specified for element "TextView".
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at android.databinding.tool.store.LayoutFileParser.stripFile(LayoutFileParser.java:412)
	at android.databinding.tool.store.LayoutFileParser.parseXml(LayoutFileParser.java:89)
	at android.databinding.tool.LayoutXmlProcessor.processSingleFile(LayoutXmlProcessor.java:157)
	at com.android.build.gradle.tasks.MergeResources$ConfigAction$1.processSingleFile(MergeResources.java:935)
	at com.android.ide.common.resources.MergedResourceWriter.end(MergedResourceWriter.java:262)
	... 119 more

```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 8]
```diff
@@ -113,6 +113,10 @@
     private static final String PARAM_PURCHASE = "add_purchase_places";
     private static final String PARAM_STORE = "add_stores";
     private static final String PARAM_COUNTRIES = "add_countries";
+    private static final String PARAM_OTHER_INFO = "other_information";
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
    private static final String PARAM_OTHER_INFORMATION = "other_information";
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 9]
```diff
@@ -113,6 +113,10 @@
...
+    private static final String PARAM_CONSERVATION_COND = "conservation_conditions";
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
    private static final String PARAM_CONSERVATION_CONDITIONS = "conservation_conditions";
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 10]
```diff
@@ -518,6 +548,18 @@ public void onError() {
                 List<String> chipValues = Arrays.asList(productDetails.get(PARAM_COUNTRIES).split("\\s*,\\s*"));
                 countriesWhereSold.setText(chipValues);
             }
+            if (productDetails.get(PARAM_OTHER_INFO) != null) {
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
            if (productDetails.get(PARAM_OTHER_INFORMATION) != null) {
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 11]
```diff
@@ -518,6 +548,18 @@ public void onError() {
...
+                otherInfo.setText(productDetails.get(PARAM_OTHER_INFO));
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
                otherInfo.setText(productDetails.get(PARAM_OTHER_INFORMATION));
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 12]
```diff
@@ -518,6 +548,18 @@ public void onError() {
...
+            }
+            if (productDetails.get(PARAM_CONSERVATION_COND) != null) {
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
            if (productDetails.get(PARAM_CONSERVATION_CONDITIONS) != null) {
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 13]
```diff
@@ -518,6 +548,18 @@ public void onError() {
...
+                conservationCond.setText(productDetails.get(PARAM_CONSERVATION_COND));
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
                conservationCond.setText(productDetails.get(PARAM_CONSERVATION_CONDITIONS));
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 14]
```diff
@@ -737,6 +779,10 @@ public void getAllDetails() {
             ((AddProductActivity) activity).addToMap(PARAM_PURCHASE.substring(4), getValues(countryWherePurchased));
             ((AddProductActivity) activity).addToMap(PARAM_STORE.substring(4), getValues(stores));
             ((AddProductActivity) activity).addToMap(PARAM_COUNTRIES.substring(4), getValues(countriesWhereSold));
+            ((AddProductActivity) activity).addToMap(PARAM_OTHER_INFO, otherInfo.getText().toString());
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
            ((AddProductActivity) activity).addToMap(PARAM_OTHER_INFORMATION, otherInfo.getText().toString());
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 15]
```diff
@@ -737,6 +779,10 @@ public void getAllDetails() {
...
+            ((AddProductActivity) activity).addToMap(PARAM_CONSERVATION_COND, conservationCond.getText().toString());
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
            ((AddProductActivity) activity).addToMap(PARAM_CONSERVATION_CONDITIONS, conservationCond.getText().toString());
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 16]
```diff
@@ -799,6 +845,18 @@ public void getDetails() {
             if (!countriesWhereSold.getChipValues().isEmpty()) {
                 ((AddProductActivity) activity).addToMap(PARAM_COUNTRIES, getValues(countriesWhereSold));
             }
+            if (!otherInfo.getText().toString().isEmpty()) {
+                ((AddProductActivity) activity).addToMap(PARAM_OTHER_INFO, otherInfo.getText().toString());
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
                ((AddProductActivity) activity).addToMap(PARAM_OTHER_INFORMATION, otherInfo.getText().toString());
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java [hunk 17]
```diff
@@ -799,6 +845,18 @@ public void getDetails() {
...
+            }
+            if (!conservationCond.getText().toString().isEmpty()) {
+                ((AddProductActivity) activity).addToMap(PARAM_CONSERVATION_COND, conservationCond.getText().toString());
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductOverviewFragment.java]:
```suggestion
                ((AddProductActivity) activity).addToMap(PARAM_CONSERVATION_CONDITIONS, conservationCond.getText().toString());
```

**Comment by teolemon** [comment]
LGTM. I'm merging. Thanks @prashantkh19 👍
