### PR TITLE
show toast when tapping on history item in offline mode

### LINKED ISSUE #2696: In case of no internet connection tapping on any product in History shoukd display a proper error message
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 
Currently tapping on any item in history, takes to the product activity Except in offline mode when nothing happens due to tapping the item. It should show a proper dialog message of no internet connection.

**Steps to reproduce:** 
- Go to History
- Switch off the internet connection
- Tap on any item

**Expected behavior:** 

A popup should appear that there is no internet connection

**Device and Android version:** 
vivo 1713 Android version 7.0

### PR DESCRIPTION
**Pull request by vanshikaarora**
## Description

In case of no internet connection show toast when user taps on any item in history tab

## Related issues and discussion
#fixes #2696 In case of no internet connection tapping on any product in History should display a proper error message
 
 ## Screen-shots, if any
 WhatsApp Image 2019-06-01 at 9 49 45 PM

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/holders/HistoryScanHolder.java [hunk 1]
```diff
@@ -42,6 +43,8 @@ public HistoryScanHolder(final View itemView, final String productUrl, Activity
             if (isConnected) {
                 OpenFoodAPIClient api = new OpenFoodAPIClient(mActivity);
                 api.getProduct(txtBarcode.getText().toString(), (Activity) v.getContext());
+            } else {
+                Toast.makeText(mActivity, "Sorry! There was a network error! Please check your internet connection", Toast.LENGTH_SHORT).show();
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/holders/HistoryScanHolder.java]: Create a new resource string instead of hardcoding it so it can be translated.
[See here](https://developer.android.com/guide/topics/resources/string-resource.html) for documentation.

Comment (vanshikaarora) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/holders/HistoryScanHolder.java]: @Vai Ton I have made the changes and squashed the commits. Please share if you have any other suggestion as well:)

Comment (teolemon) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/holders/HistoryScanHolder.java]: "The product couldn't be loaded. Please try again when you are back online." 
The popup is just hightlighting a weakness of the app (ie we should store a copy of the history for offline viewing)

Comment (vanshikaarora) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/holders/HistoryScanHolder.java]: @teolemon I have made the changes. Kindly review:)

**Comment by deniger** [comment]
@teolemon we could merge this one ?
