### PR TITLE
Closes #1870 : java.lang.IndexOutOfBoundsException in IngredientsProductFragment.

### LINKED ISSUE #1870: java.lang.IndexOutOfBoundsException - openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.access$000
```
Yesterday, 10:23 PM on app version 289
Sony Xperia XA (F3111), Android 7.0
Report 1 of 2

java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get (ArrayList.java:411)
  at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal (ViewGroup.java:3242)
  at android.view.View.onInitializeAccessibilityNodeInfo (View.java:6670)
  at android.view.View.createAccessibilityNodeInfoInternal (View.java:6629)
  at android.view.View.createAccessibilityNodeInfo (View.java:6614)
  at android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:145)
  at android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:119)
  at android.view.View.onInitializeAccessibilityEventInternal (View.java:6566)
  at android.view.View.onInitializeAccessibilityEvent (View.java:6554)
  at android.view.View.sendAccessibilityEventUncheckedInternal (View.java:6419)
  at android.view.View.sendAccessibilityEventUnchecked (View.java:6404)
  at android.view.View$SendViewStateChangedAccessibilityEvent.run (View.java:23941)
  at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost (View.java:23974)
  at android.view.View.notifyViewAccessibilityStateChangedIfNeeded (View.java:9536)
  at android.view.View.setFlags (View.java:11733)
  at android.view.View.setVisibility (View.java:8130)
  at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.access$000 (IngredientsProductFragment.java)
  or                     .getAdditiveTag (IngredientsProductFragment.java)
  or                     .lambda$onRequestPermissionsResult$0$IngredientsProductFragment (IngredientsProductFragment.java)
  or                     .onActivityResult (IngredientsProductFragment.java)
  or                     .onAttach (IngredientsProductFragment.java)
  or                     .onCreateView (IngredientsProductFragment.java)
  or                     .onPhotoReturned (IngredientsProductFragment.java)
  or                     .onRequestPermissionsResult (IngredientsProductFragment.java)
  or                     .onViewCreated (IngredientsProductFragment.java)
  or                     .refreshView (IngredientsProductFragment.java)
  or                     .setSpanBoldBetweenTokens (IngredientsProductFragment.java)
  or                     .showAdditives (IngredientsProductFragment.java)
  at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.access$000 (IngredientsProductFragment.java)
  or                     .getAdditiveTag (IngredientsProductFragment.java)
  or                     .lambda$onRequestPermissionsResult$0$IngredientsProductFragment (IngredientsProductFragment.java)
  or                     .onActivityResult (IngredientsProductFragment.java)
  or                     .onAttach (IngredientsProductFragment.java)
  or                     .onCreateView (IngredientsProductFragment.java)
  or                     .onPhotoReturned (IngredientsProductFragment.java)
  or                     .onRequestPermissionsResult (IngredientsProductFragment.java)
  or                     .onViewCreated (IngredientsProductFragment.java)
  or                     .refreshView (IngredientsProductFragment.java)
  or                     .setSpanBoldBetweenTokens (IngredientsProductFragment.java)
  or                     .showAdditives (IngredientsProductFragment.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentStopped (FragmentManagerImpl.java)
  or                     .isStateSaved (FragmentManagerImpl.java)
  or                     .moveFragmentToExpectedState (FragmentManagerImpl.java)
  or                     .reverseTransit (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.BackStackRecord.executeOps (BackStackRecord.java)
  at android.support.v4.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
  or                     .addBackStackState (FragmentManagerImpl.java)
  or                     .dispatchContextItemSelected (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentStarted (FragmentManagerImpl.java)
  or                     .dispatchOptionsMenuClosed (FragmentManagerImpl.java)
  or                     .dispatchPictureInPictureModeChanged (FragmentManagerImpl.java)
  or                     .execSingleAction (FragmentManagerImpl.java)
  or                     .executeOps (FragmentManagerImpl.java)
  or                     .findFragmentByWho (FragmentManagerImpl.java)
  or                     .getBackStackEntryAt (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .removeRedundantOperationsAndExecute (FragmentManagerImpl.java)
  or                     .setHWLayerAnimListenerIfAlpha (FragmentManagerImpl.java)
  or                     .transitToStyleIndex (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
  or                     .addBackStackState (FragmentManagerImpl.java)
  or                     .dispatchContextItemSelected (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentStarted (FragmentManagerImpl.java)
  or                     .dispatchOptionsMenuClosed (FragmentManagerImpl.java)
  or                     .dispatchPictureInPictureModeChanged (FragmentManagerImpl.java)
  or                     .execSingleAction (FragmentManagerImpl.java)
  or                     .executeOps (FragmentManagerImpl.java)
  or                     .findFragmentByWho (FragmentManagerImpl.java)
  or                     .getBackStackEntryAt (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .removeRedundantOperationsAndExecute (FragmentManagerImpl.java)
  or                     .setHWLayerAnimListenerIfAlpha (FragmentManagerImpl.java)
  or                     .transitToStyleIndex (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.addAddedFragments (FragmentManagerImpl.java)
  or                     .addBackStackState (FragmentManagerImpl.java)
  or                     .dispatchContextItemSelected (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentStarted (FragmentManagerImpl.java)
  or                     .dispatchOptionsMenuClosed (FragmentManagerImpl.java)
  or                     .dispatchPictureInPictureModeChanged (FragmentManagerImpl.java)
  or                     .execSingleAction (FragmentManagerImpl.java)
  or                     .executeOps (FragmentManagerImpl.java)
  or                     .findFragmentByWho (FragmentManagerImpl.java)
  or                     .getBackStackEntryAt (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .removeRedundantOperationsAndExecute (FragmentManagerImpl.java)
  or                     .setHWLayerAnimListenerIfAlpha (FragmentManagerImpl.java)
  or                     .transitToStyleIndex (FragmentManagerImpl.java)
  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss (BackStackRecord.java)
  at android.support.v4.app.FragmentPagerAdapter.finishUpdate (FragmentPagerAdapter.java)
  or                     .getItemId (FragmentPagerAdapter.java)
  or                     .setPrimaryItem (FragmentPagerAdapter.java)
  at android.support.v4.view.ViewPager.addNewItem (ViewPager.java)
  or                     .addOnAdapterChangeListener (ViewPager.java)
  or                     .addOnPageChangeListener (ViewPager.java)
  or                     .calculatePageOffsets (ViewPager.java)
  or                     .canScroll (ViewPager.java)
  or                     .completeScroll (ViewPager.java)
  or                     .determineTargetPage (ViewPager.java)
  or                     .distanceInfluenceForSnapDuration (ViewPager.java)
  or                     .executeKeyEvent (ViewPager.java)
  or                     .getChildRectInPagerCoordinates (ViewPager.java)
  or                     .infoForChild (ViewPager.java)
  or                     .initViewPager (ViewPager.java)
  or                     .isGutterDrag (ViewPager.java)
  or                     .onPageScrolled (ViewPager.java)
  or                     .onSecondaryPointerUp (ViewPager.java)
  or                     .populate (ViewPager.java)
  or                     .recomputeScrollPosition (ViewPager.java)
  or                     .scrollToItem (ViewPager.java)
  or                     .setCurrentItem (ViewPager.java)
  or                     .setCurrentItemInternal (ViewPager.java)
  or                     .smoothScrollTo (ViewPager.java)
  at android.support.v4.view.ViewPager.arrowScroll (ViewPager.java)
  or                     .isDecorView (ViewPager.java)
  or                     .populate (ViewPager.java)
  or                     .requestParentDisallowInterceptTouchEvent (ViewPager.java)
  at android.support.v4.view.ViewPager.onMeasure (ViewPager.java)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.support.design.widget.CoordinatorLayout.constrainChildRect (CoordinatorLayout.java)
  or                     .ensurePreDrawListener (CoordinatorLayout.java)
  or                     .generateLayoutParams (CoordinatorLayout.java)
  or                     .getChildRect (CoordinatorLayout.java)
  or                     .getDescendantRect (CoordinatorLayout.java)
  or                     .getDesiredAnchoredChildRect (CoordinatorLayout.java)
  or                     .getDesiredAnchoredChildRectWithoutConstraints (CoordinatorLayout.java)
  or                     .getResolvedLayoutParams (CoordinatorLayout.java)
  or                     .getTopSortedChildren (CoordinatorLayout.java)
  or                     .isPointInChildBounds (CoordinatorLayout.java)
  or                     .layoutChildWithAnchor (CoordinatorLayout.java)
  or                     .offsetChildByInset (CoordinatorLayout.java)
  or                     .onChildViewsChanged (CoordinatorLayout.java)
  or                     .onLayoutChild (CoordinatorLayout.java)
  or                     .onMeasureChild (CoordinatorLayout.java)
  or                     .onNestedPreScroll (CoordinatorLayout.java)
  or                     .onNestedScroll (CoordinatorLayout.java)
  or                     .onStartNestedScroll (CoordinatorLayout.java)
  or                     .parseBehavior (CoordinatorLayout.java)
  or                     .performIntercept (CoordinatorLayout.java)
  or                     .releaseTempRect (CoordinatorLayout.java)
  or                     .resetTouchBehaviors (CoordinatorLayout.java)
  or                     .setWindowInsets (CoordinatorLayout.java)
  at android.support.design.widget.HeaderScrollingViewBehavior.getOverlapRatioForOffset (HeaderScrollingViewBehavior.java)
  or                     .getVerticalLayoutGap (HeaderScrollingViewBehavior.java)
  or                     .onMeasureChild (HeaderScrollingViewBehavior.java)
  at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.findFirstDependency (AppBarLayout.java)
  or                     .getAppBarLayoutOffset (AppBarLayout.java)
  or                     .getOverlapRatioForOffset (AppBarLayout.java)
  or                     .layoutDependsOn (AppBarLayout.java)
  or                     .onLayoutChild (AppBarLayout.java)
  or                     .onMeasureChild (AppBarLayout.java)
  or                     .onRequestChildRectangleOnScreen (AppBarLayout.java)
  or                     .setTopAndBottomOffset (AppBarLayout.java)
  at android.support.design.widget.CoordinatorLayout.onMeasure (CoordinatorLayout.java)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:214)
  at android.support.v7.widget.ContentFrameLayout.onMeasure (ContentFrameLayout.java)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1705)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:797)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:657)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:214)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.widget.LinearLayout.measureChildBeforeLayout (LinearLayout.java:1705)
  at android.widget.LinearLayout.measureVertical (LinearLayout.java:797)
  at android.widget.LinearLayout.onMeasure (LinearLayout.java:657)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewGroup.measureChildWithMargins (ViewGroup.java:6282)
  at android.widget.FrameLayout.onMeasure (FrameLayout.java:214)
  at com.android.internal.policy.DecorView.onMeasure (DecorView.java:714)
  at android.view.View.measure (View.java:20132)
  at android.view.ViewRootImpl.performMeasure (ViewRootImpl.java:2640)
  at android.view.ViewRootImpl.measureHierarchy (ViewRootImpl.java:1577)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1846)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1462)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6965)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:907)
  at android.view.Choreographer.doCallbacks (Choreographer.java:709)
  at android.view.Choreographer.doFrame (Choreographer.java:644)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:893)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6361)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
```

### PR DESCRIPTION
**Pull request by jaindiv26**
## Description
Rectify the for loop condition. As the previous condition fail to put the last allergen on the list(line: 293), so when accessed the last allergen(line: 299) it was causing the java.lang.IndexOutOfBoundsException.

## Related issues and discussion
#1870 : java.lang.IndexOutOfBoundsException in IngredientsProductFragment.

### CODE REVIEW

**Comment by teolemon** [comment]
hey @brandenfung can you review this one ?

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ingredients/IngredientsProductFragment.java [hunk 1]
```diff
@@ -290,7 +290,7 @@ public void refreshView(State state) {
             substanceProduct.append(" ");
 
             String allergen;
-            for (int i = 0; i < allergens.size() - 1; i++) {
+            for (int i = 0; i <= allergens.size() - 1; i++) {
```
Comment (Karljoones) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ingredients/IngredientsProductFragment.java]: This should actually read as the following `for (int i = 0; i < allergens.size(); i++)`

Comment (jaindiv26) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ingredients/IngredientsProductFragment.java]: @Karljoones I'll change the loop condition.
