### PR TITLE
fix: "No nutrition facts" switch not working as intended

### LINKED ISSUE #4582: The "No Nutrition facts" toggle does not work correctly
### What
- The "No Nutrition facts" toggle does not work correctly

### Part of
- #4166 

### Video
https://user-images.githubusercontent.com/1689815/159445100-18216220-e401-427e-bb03-4d3ffc579b03.mp4

### PR DESCRIPTION
**Pull request by g123k**
PR that fixes two issues:
- If Nutrition data is set to OFF, the table beneath shouldn't be displayed
- If Nutrition data is set to OFF, no nutritional data is sent to the API

 #4582

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt [hunk 1]
```diff
@@ -551,10 +555,11 @@ class ProductEditNutritionFactsFragment : ProductEditFragment() {
         // Add no nutrition data entry to map
         if (binding.checkboxNoNutritionData.isChecked) {
             targetMap[ApiFields.Keys.NO_NUTRITION_DATA] = "on"
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: So we send the boolean to deactivate, but do we send the boolean to reactivate, along or before nutrients ?

Comment (g123k) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: You're right, this is not the case right now.

Currently in the code, the app checks if the field is null (= no nutrition data) or == "ON"
So I will just send a null in the other cases. Otherwise I am afraid of generating some bugs

Comment (g123k) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: That should be OK right now, with the new commit [#9ce02dd](https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/4583/commits/9ce02dd82ef53fbaf27f6126513ca9141e652a7c)

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt [hunk 2]
```diff
@@ -575,6 +575,10 @@ class ProductEditNutritionFactsFragment : ProductEditFragment() {
             targetMap += getNutrientMapIfUpdated(view)
         }
 
+        // We force a null value here for "no nutrition", instead of an "off" String,
+        // to be sure to do not break other apps
+        targetMap[ApiFields.Keys.NO_NUTRITION_DATA] = null
```
Comment (teolemon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: ?

Comment (teolemon) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt:580]: @stephanegigandet what are the expected values ? I'm opening some documentation issue on this

Comment (teolemon) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: @g123k : https://github.com/openfoodfacts/api-documentation/issues/70

Comment (g123k) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/edit/nutrition/ProductEditNutritionFactsFragment.kt]: Look at line 335, on Android the check is if != null -> true

I have improved the checks to ensure, "on" is true and everything else is false

**Comment by g123k** [comment]
The code should now be OK with comments from https://github.com/openfoodfacts/api-documentation/issues/70

**Comment by teolemon** [comment]
thank you @g123k , merging and releasing to internal 👍
