### PR TITLE
Show lists the product belongs to on the product page 

### LINKED ISSUE #3458: Show lists of a product on the product
- [ ] Show lists which the product is part of. If we add a product to a list, we should see it on the product page.
- [ ] When clicking on a chip, the user should be redirected to the list view.

We fixed this in this PR that did not work: https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2271

### PR DESCRIPTION
**Pull request by kartikaysharma01**
####  Description
Displayed list of user for a product on product page . Used material component chips for implementation.

#### Related issues

Fixes #3458 

#### Screenshots

localhost_5901 (android-dev-instance asia-southeast1-b c android-dev-301317 internal_1 (sharm)) - VNC Viewer 2021-01-20 00-41-21

### CODE REVIEW

**Comment by VaiTon** [comment]
Only a comment about the design: I'd like it more if they were on a single line and scrollable.
@teolemon what do you think?

**Comment by kartikaysharma01** [comment]
> Only a comment about the design: I'd like it more if they were on a single line and scrollable.
> @teolemon what do you think?

I too wanted to implement that but we are already having a horizontal swipe on that page, so it might confuse users.
Should I make it a horizontal scroll ?

**Comment by VaiTon** [comment]
> 
> 
> > Only a comment about the design: I'd like it more if they were on a single line and scrollable.
> > @teolemon what do you think?
> 
> I too wanted to implement that but we are already having a horizontal swipe on that page, so it might confuse users.
> Should I make it a horizontal scroll ?

Please do it 🚀

**Comment by kartikaysharma01** [comment]
image
@VaiTon I have pushed the changes . Thanks.

**Comment by teolemon** [comment]
image

**Comment by VaiTon** [comment]
> 
> 
> image

Hmmm, maybe it makes more sense. @kartikaysharma01 what do you think?

**Comment by kartikaysharma01** [comment]
What will be the flow if the user wants to add the product to a new list ?

**Comment by kartikaysharma01** [comment]
Maybe we can change the position to as shown by @teolemon but keep the add to list button as it is.

**Comment by kartikaysharma01** [comment]
image
Views? @teolemon @VaiTon

**Comment by VaiTon** [comment]
I don't like the gray, could we use a "more white" white or even a light gray

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 1]
```diff
@@ -462,6 +474,44 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
         }
     }
 
+    private fun showListChips() {
+
+        // remove the existing childviews on chip group if any
+        binding.listChips.removeAllViews()
+
+        val listDao: YourListedProductDao = OFFApplication.daoSession.yourListedProductDao
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Is it useful to have this explicit type?

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 2]
```diff
@@ -462,6 +474,44 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
...
+
+        //Query to check if the product belons in any of thr user's list
+        val queryResult : List<YourListedProduct> = listDao.queryBuilder()
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: This operation is on the main thread, we do not want it.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 3]
```diff
@@ -462,6 +474,44 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
...
+                .where(YourListedProductDao.Properties.Barcode.eq(product.code)).list()
+
+        if (queryResult.isNullOrEmpty()) {
+            binding.listChips.visibility = View.GONE
+            return
+        }
+
+        binding.listChips.visibility = View.VISIBLE
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: You could add an else branch to the precedent statement.

**Review by VaiTon — CHANGES_REQUESTED** [review]

**Comment by kartikaysharma01** [comment]
> I don't like the gray, could we use a "more white" white or even a light gray

Yes I will add a lighter tone of grey. Is the layout fine ?

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt (hunk 3 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Ok. I will do that. Thanks.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt (hunk 1 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: No. I removed it.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt (hunk 2 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Changed the thread. Will push the change after layout is finalized.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt (hunk 3 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt:493]: > I don't like the gray, could we use a "more white" white or even a light gray

image

@teolemon @VaiTon Is this fine?

**Comment by kartikaysharma01** [comment]
> I don't like the gray, could we use a "more white" white or even a light gray

image

@VaiTon @teolemon Is this fine?

**Comment by VaiTon** [comment]
@kartikaysharma01 yes it is. Thank you for your work.

**Comment by kartikaysharma01** [comment]
@VaiTon changes pushed. Let me know if there is any change to be made. Thanks.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 4]
```diff
@@ -462,6 +477,45 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
...
+        // remove the existing childviews on chip group if any
+        binding.listChips.removeAllViews()
+
+        val asyncSessionList = OFFApplication.daoSession.startAsyncSession()
+        asyncSessionList.queryList(OFFApplication.daoSession.yourListedProductDao.queryBuilder()
+                .where(YourListedProductDao.Properties.Barcode.eq(product.code)).build())
+
+        val queryResult= arrayListOf<YourListedProduct>()
+        asyncSessionList.listenerMainThread = AsyncOperationListener { operation ->
+            (operation.result as List<YourListedProduct> ).mapTo(queryResult) {it}
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Why do you map to another array list? Can't we use this one?

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt [hunk 5]
```diff
@@ -462,6 +477,45 @@ class SummaryProductFragment : BaseFragment(), ISummaryProductPresenter.View {
...
+                    chip.text = list.listName
+
+                    // set a random color to the chip's background, we want a dark background as our text color is white so we will limit our rgb to 180
+                    val chipColor: Int = Color.rgb(Random.nextInt(180),Random.nextInt(180),Random.nextInt(180) )
+                    chip.chipBackgroundColor = ColorStateList.valueOf(chipColor)
+                    chip.setTextColor(Color.WHITE)
+
+                    // open list when the user clicks on chip
+                    chip.setOnClickListener {
+                        activity?.startActivity(Intent(activity, ProductListActivity::class.java).apply {
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: I think it would be better if we used `ProductListActivity.start`

**Review by VaiTon — CHANGES_REQUESTED** [review]

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt (hunk 5 above)
Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Looking into it.

Comment (kartikaysharma01) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/summary/SummaryProductFragment.kt]: Yup, ```ProductListActivity.start``` is a better chioice. Thanks.

**Comment by kartikaysharma01** [comment]
@VaiTon I have pushed the changes. Please give it a look.

**Review by VaiTon — APPROVED** [review]
Good job! 🎉
