### PR TITLE
Fix crash caused by ISE on the 3 screens

### LINKED ISSUE #3559: IllegalStateException : attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
**Describe the bug**
startActivityForResult() was depreciated. The replacement for that was recently done in the code but not implemented correctly causing ISE. 
**To Reproduce**
1. Click to menu item **Sign in** from drawer on home screen - will experience a crash.
The same crash is being experienced at different places in the App. Few noticed ones are
a. Search a valid product on home screen .
b. Click on the product that comes in the search result.
c. Go to INGREDIENTS tab.
d. Click on edit. 
    i) If you are logged in - will experience a crash.
    ii) Not logged in - Click on Sign In on the pop up - will experience a crash

**Expected behavior**
Respective screens should open.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
**LOG**
java.lang.IllegalStateException: LifecycleOwner openfoodfacts.github.scrachx.openfood.features.MainActivity@91ab37b is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.

### PR DESCRIPTION
**Pull request by sarah541**
####  Description
startActivityForResult() was depreciated. The replacement for that was recently done in the code but not implemented correctly causing ISE.
Documentation : https://developer.android.com/training/basics/intents/result

#### Related issues
Closes #3559

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.java [hunk 1]
```diff
@@ -158,6 +160,13 @@
     private String barcode;
     private PrefManager prefManager;
     private CompositeDisposable disp;
+    ActivityResultLauncher<Void> loginActivityResultLauncher = registerForActivityResult(
+        new LoginActivity.LoginContract(),
+        (ActivityResultCallback<Boolean>) result -> {
+            if (result){
```
Comment (huzaifaiftikhar) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/MainActivity.java]:
```suggestion
        (ActivityResultCallback<Boolean>) isLoggedIn -> {
            if (isLoggedIn) {
```

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/features/scan/ContinuousScanActivity.java [hunk 2]
```diff
@@ -159,6 +162,11 @@
     private SummaryProductPresenter summaryProductPresenter;
     private Disposable hintBarcodeDisp;
     private CompositeDisposable commonDisp;
+    ActivityResultLauncher<Intent> productActivityResultLauncher = registerForActivityResult(
+        new ActivityResultContracts.StartActivityForResult(),
+        (ActivityResultCallback<ActivityResult>) result -> {
+            setShownProduct(lastBarcode);
```
Comment (huzaifaiftikhar) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/features/scan/ContinuousScanActivity.java]:
```suggestion
            if (result.getResultCode() == RESULT_OK) {	
                setShownProduct(lastBarcode);	
            }
```

**Review by huzaifaiftikhar — APPROVED** [review]

**Comment by teolemon** [comment]
Thanks @sarah541 👍
