### PR TITLE
Fixes issue #2118: Added a fast addition mode

### LINKED ISSUE #2118: Create a fast addition mode
It would only require 3 photos, product name, brand and weight.

### PR DESCRIPTION
**Pull request by prashantkh19**
## Description
Added an option in preferences to enable fast addition mode and made changes accordingly to have a fast addition mode if enabled in preferences.

## Related issues and discussion
#fixes #2118 
 
 ## Screen-shots
 
screenshot_2019-01-19-21-08-02-597_openfoodfacts github scrachx openfood
screenshot_2019-01-19-21-07-47-046_openfoodfacts github scrachx openfood
screenshot_2019-01-19-21-07-54-277_openfoodfacts github scrachx openfood

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductIngredientsFragment.java [hunk 1]
```diff
@@ -193,6 +207,25 @@ private String getTracesName(String languageCode, String tag) {
         return tag;
     }
 
+    /**
+     * To enable fast addition mode
+     *
+     * @param is
+     */
+    private void enableFastAdditionMode(boolean is) {
```
Comment (PrajwalM2212) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductIngredientsFragment.java]: boolean `is` could be more descriptive like `isEnabled` . But it is upto to you.

Comment (prashantkh19) [reply app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/AddProductIngredientsFragment.java]: Thanks for the suggestion. `isEnabled` is surely more descriptive, I will update it.
