### PR TITLE
Fixed Permission bug

### LINKED ISSUE #3762: Allowing permission but a dialog box appears asking to activate it
**Describe the bug**
Inspite of allowing the permission during runtime, a dialog box appears to activate the permission from settings. (Permission is actually)

**To Reproduce**
1. Open any product
2. Click on _Take extra photos of packaging_ in Summary Tab.
3. Allow the permission.

**Expected behavior**
The camera must open.

### PR DESCRIPTION
**Pull request by mrudultora**
####  Description
Fixed the dialog box to appear only when permission is denied. Or else, opens the camera.

#### Related issues
Fixes #3762 

#### Related PRs
None

#### Screenshots

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/Utils.kt [hunk 1]
```diff
@@ -310,7 +310,7 @@ object Utils {
 
 }
 
-fun isAllGranted(grantResults: Map<String?, Boolean?>) = grantResults.containsValue(false)
+fun isAllGranted(grantResults: Map<String?, Boolean?>) = grantResults.containsValue(true)
```
Comment (VaiTon) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/utils/Utils.kt]: We need to check for every result.
You should use:
```suggestion
fun isAllGranted(grantResults: Map<String?, Boolean?>) = !grantResults.containsValue(false)
```

**Review by VaiTon — CHANGES_REQUESTED** [review]

**Review by VaiTon — APPROVED** [review]

**Comment by VaiTon** [comment]
Thank you! 🎉
