### PR TITLE
Fixes #1761 Unexpected login of user

### LINKED ISSUE #1761: Unexpected Login of user
User enters wrong credentials then also when again entering the app it shows "Logout.." instead of "Sign in" in side menu. 

How can we reproduce the issue?

First enter wrong credentials for eg: username = "abcdefgh" password = "abcdefgh".

screenshot_2018-07-02-15-15-47-490_openfoodfacts github scrachx openbeauty

Now press the sign in button and as expected it shows error of "username or password is incorrect".

screenshot_2018-07-02-15-13-08-680_openfoodfacts github scrachx openbeauty

Now close the app and again open it and press the navigation button from the homepage and it can be noticed that there is "Logout" written instead of "Sign in".There should be sign in as the credentials were wrong.

screenshot_2018-07-02-15-14-21-397_org openfoodfacts scanner

Now press that "Logout" choice and it can be noticed that dialog box appears "Are you sure you want to logout ?"

screenshot_2018-07-02-15-14-28-595_org openfoodfacts scanner

What did you expect the app to do?

According to me this there should not be "Logout" as user have not registered yet. 

Xiaomi Redmi Note 4 , Android version 7.0 , API 24

### PR DESCRIPTION
**Pull request by Rutvikmodi**

### CODE REVIEW

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java [hunk 1]
```diff
@@ -88,21 +88,21 @@ protected void onCreate(Bundle savedInstanceState) {
...
         customTabActivityHelper.setConnectionCallback(this);
         customTabActivityHelper.mayLaunchUrl(userLoginUri, null, null);
-
-        signup.setEnabled(false);
+        signup.setEnabled(true);
 
         final SharedPreferences settings = getSharedPreferences("login", 0);
         String loginS = settings.getString("user", getResources().getString(R.string.txt_anonymous));
-        if (!loginS.equals(getResources().getString(R.string.txt_anonymous))) {
+        if (loginS.equals("user")) {
```
Comment (ross-holloway94) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/LoginActivity.java]: Please use a string resource here rather than the hardcoded string "user". This allows the app to be multilingual.

File: app/src/main/java/openfoodfacts/github/scrachx/openfood/views/MainActivity.java [hunk 2]
```diff
@@ -267,10 +271,10 @@ public boolean onClick(View view, IProfile profile) {
 
         // Add Manage Account profile if the user is connected
         SharedPreferences preferences = getSharedPreferences("login", 0);
-        String userLogin = preferences.getString("user", null);
+        userLogin = preferences.getString("user", null);
```
Comment (ross-holloway94) [inline app/src/main/java/openfoodfacts/github/scrachx/openfood/views/MainActivity.java]: See my other comment about hardcoded strings.

File: README.md [hunk 3]
```diff
@@ -13,10 +13,21 @@ Open Food Facts Android Application
 ## What is Open Food Facts?
 
 <a href="https://f-droid.org/app/openfoodfacts.github.scrachx.openfood"><img src="https://f-droid.org/badge/get-it-on.png" alt="Get it on F-Droid" height="70"></a><a href="https://play.google.com/store/apps/details?id=org.openfoodfacts.scanner"><img src="https://play.google.com/intl/en_us/badges/images/badge_new.png" alt="Get it on the Google Play Store" height="70"></a><br>
+<<<<<<< HEAD
+<<<<<<< HEAD
+(These are beta versions, <a href="https://play.google.com/store/apps/details?id=org.openfoodfacts.scanner">this is the stable version</a>)
+=======
+=======
+
+>>>>>>> bac47391e36208358d3f6382c3ade0f6871ab3f5
```
Comment (Karljoones) [inline README.md]: The above needs to be fixed

File: README.md [hunk 4]
```diff
@@ -13,10 +13,21 @@ Open Food Facts Android Application
...
 <img src="https://lh3.googleusercontent.com/PYEw9fMLJ5ETPqB2mxeekfVTTNOkJHscs4MRHo546GJzwgIoj3SiJFsZDx4_D-EAUA=w720-h310-rw" height="300">
 <img src="https://lh3.googleusercontent.com/q7NWz-hc4x39q8N7EW0cz5GZDHN5-F0ttZPHFPvf8-cTG2RImWi_C2J7zCY1Wtc_qZw=w1280-h636-rw" height="300">
 <img src="https://lh3.googleusercontent.com/HXGodB99lZDp3lusX4ZdnkKJxcKiFv5ohfvaiMB7iX-i_QrcvWzUXPxmlSp8nq8SkBc=w1280-h636-rw" height="300">
 <img src="https://lh3.googleusercontent.com/t_AWYLEzr2O4n7KVli8GV_gpT_N1FKhq5EwReUvJjXdJNoPTBTwD-3cKTfZUrkyQAMM=w1280-h636-rw" height="300">
+<<<<<<< HEAD
+>>>>>>> 96bd41f6cc92a74f984e8569edf815dc6df86415
+=======
+>>>>>>> bac47391e36208358d3f6382c3ade0f6871ab3f5
```
Comment (Karljoones) [inline README.md]: This also needs to be fixed

**Comment by ross-holloway94** [comment]
@Karljoones I have helped Rutvikmodi rebase this PR and remove the unwanted commits. Please could you review the code again? :)

**Comment by Karljoones** [comment]
Looks good to me @ross-holloway94, thanks for the code @Rutvikmodi
